package com.wealthsense.android.ml

import android.content.Context
import org.tensorflow.lite.Interpreter
import java.io.FileInputStream
import java.nio.MappedByteBuffer
import java.nio.channels.FileChannel

/**
 * Hybrid merchant category classifier.
 *
 * Primary path: a small trained TFLite model (see /ml_training in the repo root
 * for the training script) scores each of the 8 categories from a bag-of-words
 * encoding of the merchant text.
 *
 * Fallback path: a hardcoded keyword matcher, used whenever the model isn't
 * available (empty/missing asset) OR the model's top prediction isn't confident
 * enough to trust. This keeps the app useful even before a model is trained,
 * and keeps predictions sane for merchants the small training set never saw.
 *
 * IMPORTANT: `vocab` below MUST exactly match ml_training/vocab.json, which is
 * generated by ml_training/build_vocab.py from ml_training/dataset.py. If you
 * regenerate the dataset/vocab, update this map to match, or the model's
 * predictions will be meaningless (right features landing in wrong positions).
 */
class CategoryClassifier(context: Context) {
    private var interpreter: Interpreter? = null

    // Bag-of-words vocabulary: word -> input vector position. Generated by
    // ml_training/build_vocab.py - keep in sync with ml_training/vocab.json.
    private val vocab = mapOf(
        "amazon" to 0, "bill" to 1, "india" to 2, "recharge" to 3, "reliance" to 4,
        "swiggy" to 5, "airtel" to 6, "jio" to 7, "payment" to 8, "store" to 9,
        "tata" to 10, "uber" to 11, "zomato" to 12, "1mg" to 13, "apollo" to 14,
        "basket" to 15, "bike" to 16, "blinkit" to 17, "board" to 18, "card" to 19,
        "coffee" to 20, "credit" to 21, "dominos" to 22, "donation" to 23, "electricity" to 24,
        "flipkart" to 25, "gas" to 26, "healthifyme" to 27, "hospital" to 28, "hotstar" to 29,
        "indian" to 30, "instamart" to 31, "ltd" to 32, "metro" to 33, "myntra" to 34,
        "netflix" to 35, "nykaa" to 36, "ola" to 37, "petrol" to 38, "pharmacy" to 39,
        "practo" to 40, "premium" to 41, "prime" to 42, "rapido" to 43, "spotify" to 44,
        "starbucks" to 45, "technologies" to 46, "transfer" to 47, "zepto" to 48
    )

    // Must match ml_training/dataset.py CATEGORIES order exactly - the model's
    // output at index i corresponds to categories[i].
    private val categories = listOf(
        "Food", "Groceries", "Shopping", "Transport", "Bills", "Entertainment", "Health", "Miscellaneous"
    )

    // Below this confidence, don't trust the model - use the keyword fallback instead.
    private val confidenceThreshold = 0.55f

    init {
        try {
            val fileBuffer = loadModelFile(context, "model.tflite")
            // Prevent crashes during testing if the local asset file is empty (0 bytes)
            if (fileBuffer.capacity() > 0) {
                interpreter = Interpreter(fileBuffer)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private fun loadModelFile(context: Context, modelName: String): MappedByteBuffer {
        val fileDescriptor = context.assets.openFd(modelName)
        val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
        val fileChannel = inputStream.channel
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, fileDescriptor.startOffset, fileDescriptor.declaredLength)
    }

    fun classifyMerchant(merchantName: String): String {
        val model = interpreter
        if (model == null) {
            return fallbackHeuristicClassifier(merchantName)
        }

        try {
            val inputVector = encodeBagOfWords(merchantName)
            val outputArray = Array(1) { FloatArray(categories.size) }
            model.run(arrayOf(inputVector), outputArray)

            val scores = outputArray[0]
            val maxIndex = scores.indices.maxByOrNull { scores[it] } ?: 0
            val confidence = scores[maxIndex]

            return if (confidence >= confidenceThreshold) {
                categories[maxIndex]
            } else {
                // Model isn't confident (e.g. merchant text it never saw in training) -
                // trust the keyword rules instead of guessing.
                fallbackHeuristicClassifier(merchantName)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            return fallbackHeuristicClassifier(merchantName)
        }
    }

    /** Multi-hot bag-of-words vector: 1.0 at position i if vocab word i is present. */
    private fun encodeBagOfWords(merchantName: String): FloatArray {
        val vector = FloatArray(vocab.size)
        val tokens = merchantName.lowercase().split(Regex("[^a-z0-9]+")).filter { it.isNotBlank() }
        for (token in tokens) {
            vocab[token]?.let { index -> vector[index] = 1.0f }
        }
        return vector
    }

    // Keyword-based fallback. Used when the model isn't loaded, or when it's
    // unsure. Extend these lists as you notice miscategorized merchants.
    private fun fallbackHeuristicClassifier(merchantName: String): String {
        val name = merchantName.lowercase()
        return when {
            name.contains("swiggy") || name.contains("zomato") || name.contains("eats") ||
                name.contains("dominos") || name.contains("mcdonald") || name.contains("kfc") ||
                name.contains("burger") || name.contains("starbucks") || name.contains("cafe") ||
                name.contains("restaurant") -> "Food"

            name.contains("blinkit") || name.contains("zepto") || name.contains("instamart") ||
                name.contains("bigbasket") || name.contains("dmart") || name.contains("kirana") ||
                name.contains("grocery") || name.contains("jiomart") -> "Groceries"

            name.contains("amazon") || name.contains("flipkart") || name.contains("myntra") ||
                name.contains("ajio") || name.contains("nykaa") || name.contains("meesho") ||
                name.contains("croma") || name.contains("decathlon") -> "Shopping"

            name.contains("uber") || name.contains("ola") || name.contains("rapido") ||
                name.contains("irctc") || name.contains("metro") || name.contains("petrol") ||
                name.contains("fastag") || name.contains("parking") -> "Transport"

            name.contains("airtel") || name.contains("jio") || name.contains("vodafone") ||
                name.contains("electricity") || name.contains("bescom") || name.contains("gas") ||
                name.contains("broadband") || name.contains("lic") || name.contains("card bill") ||
                name.contains("recharge") -> "Bills"

            name.contains("netflix") || name.contains("spotify") || name.contains("hotstar") ||
                name.contains("prime video") || name.contains("bookmyshow") || name.contains("pvr") ||
                name.contains("inox") || name.contains("youtube") -> "Entertainment"

            name.contains("pharmacy") || name.contains("apollo") || name.contains("practo") ||
                name.contains("netmeds") || name.contains("1mg") || name.contains("hospital") ||
                name.contains("clinic") || name.contains("cult") || name.contains("healthifyme") -> "Health"

            else -> "Miscellaneous"
        }
    }
}
